"""Fetch GitHub star data for the OpenMOSS project series.

Writes assets/js/gh-stars-data.js, which defines a single global:

    window.__GH_STARS__ = {
      generated_at: "2026-06-05T04:00:00Z",
      repos: {},                     # reserved for single-repo entries
      orgs: {
        OpenMOSS: [
          { name: "MOSS", stars: 12121,
            url: "https://github.com/OpenMOSS/MOSS", desc: "..." },
          ...
        ],
        ...
      }
    }

The SPA (assets/js/spa.js) reads this global on the Resources page and
hydrates the project-series cards, exactly mirroring the personal
homepage's star-counter.js (baked -> localStorage cache -> live API).

This site has no Jekyll build, so we emit JS directly (no YAML step) and
depend only on the Python standard library. Run on CI with GITHUB_TOKEN
in the environment for the higher rate limit; it also works
unauthenticated locally (60 req/hour per IP).
"""
from __future__ import annotations

import datetime
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

API = "https://api.github.com"
TOKEN = os.environ.get("GITHUB_TOKEN", "").strip()
ROOT = Path(__file__).resolve().parent.parent

# GitHub orgs backing each project series shown on the Resources page.
# Keep in sync with SPA_DATA.projectSeries[*].org in assets/js/content-data.js.
ORGS = ["OpenMOSS", "nndl", "FudanNLP", "nex-agi"]


def gh(path: str):
    req = urllib.request.Request(
        API + path,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "openmoss-stars-fetcher",
        },
    )
    if TOKEN:
        req.add_header("Authorization", f"Bearer {TOKEN}")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())


def list_org_repos(org: str) -> list[dict]:
    repos: list[dict] = []
    for page in range(1, 11):  # up to 1000 repos
        batch = gh(f"/orgs/{org}/repos?per_page=100&type=public&page={page}")
        if not batch:
            break
        repos.extend(batch)
        if len(batch) < 100:
            break

    out = []
    for r in repos:
        if r.get("fork") or r.get("archived") or r.get("private"):
            continue
        out.append(
            {
                "name": r["name"],
                "stars": r.get("stargazers_count") or 0,
                "url": r["html_url"],
                "desc": r.get("description") or "",
            }
        )
    out.sort(key=lambda x: x["stars"], reverse=True)
    return out


def main() -> int:
    orgs: dict[str, list[dict]] = {}
    errors = 0

    for org in ORGS:
        try:
            orgs[org] = list_org_repos(org)
            total = sum(r["stars"] for r in orgs[org])
            print(f"org {org}: {len(orgs[org])} public repos, {total} stars")
        except Exception as e:  # noqa: BLE001 — one bad org shouldn't fail the build
            errors += 1
            print(f"!! org {org}: {e}", file=sys.stderr)

    payload = {
        "generated_at": datetime.datetime.now(datetime.UTC).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        ),
        "repos": {},
        "orgs": orgs,
    }

    out_path = ROOT / "assets" / "js" / "gh-stars-data.js"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    out_path.write_text(
        "/* Auto-generated by scripts/fetch_stars.py — do not edit by hand. */\n"
        f"window.__GH_STARS__ = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {out_path}")

    # Non-fatal: surface errors but don't break the deploy over a flaky org.
    return 0


if __name__ == "__main__":
    sys.exit(main())
